language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y update
install:
  - sudo apt-get install -qq gnulib #stdbool.m4 is required for AC_CHECK_HEADER_STDBOOL in configure.ac
  - ACLOCAL_ARGS="-I/usr/share/gnulib/m4" ./autogen.sh
  - ./configure
  - make
script:
  - make check

notifications:
  emails:
    - klang-project@kmc.gr.jp
  on_success: change
  on_failure: always
